### ISSUE TITLE
Different combinations of 'title' and 'row' data will cause TableRex to crash.

### ISSUE THREAD

**Issue by justingamble** [djm/table_rex#22]
Here is an example.
Test code:

``` elixir
defmodule Tablerexbug do
  @moduledoc """
  Documentation for Tablerexbug.
  """

  def table_ok1 do
    title = "abcdefghijklmnopqrstuvwxyz12"
    headers = [ "ID", "Test case name" ]
    rows = [["1", "abcdefghijklmnopqrstu"]]

    aString = TableRex.Table.new(rows, headers, title)
      |> TableRex.Table.render!(horizontal_style: :header)

    IO.puts(aString)
  end

  def table_ok2 do
    title = "abcdefghijklmnopqrstuvwxyz123456788"  
    headers = [ "ID", "Test case name" ]
    rows = [["1", "abcdefghi          jklmnopqrstu"]]

    aString = TableRex.Table.new(rows, headers, title)
      |> TableRex.Table.render!(horizontal_style: :header)

    IO.puts(aString)
  end

  # table_fail: 
  # this is the same as 'table_ok1()', except that the title is longer
  # this is the same as 'table_ok2()', except that the rows data is shorter
  def table_fail do
    title = "abcdefghijklmnopqrstuvwxyz123456788" 
    headers = [ "ID", "Test case name" ]
    rows = [["1", "abcdefghijklmnopqrstu"]]

    aString = TableRex.Table.new(rows, headers, title)
      |> TableRex.Table.render!(horizontal_style: :header)

    IO.puts(aString)
  end

  def main do
    IO.puts("Program started\n")
    IO.puts("Table_ok1:\n")
    table_ok1()

    IO.puts("Table_ok2:\n")
    table_ok2()

    IO.puts("Table_fail:\n")
    table_fail()
  end
end
```

Execution Output:
```
Compiling 1 file (.ex)
Program started

Table_ok1:

+----------------------------+
|abcdefghijklmnopqrstuvwxyz12|
+----+-----------------------+
| ID | Test case name        |
+----+-----------------------+
| 1  | abcdefghijklmnopqrstu |
+----+-----------------------+

Table_ok2:

+--------------------------------------+
| abcdefghijklmnopqrstuvwxyz123456788  |
+----+---------------------------------+
| ID | Test case name                  |
+----+---------------------------------+
| 1  | abcdefghi          jklmnopqrstu |
+----+---------------------------------+

Table_fail:

** (ArgumentError) argument error
    (stdlib) :binary.copy(" ", -3)
    (table_rex) lib/table_rex/renderer/text.ex:233: TableRex.Renderer.Text.do_render_cell/4
    (table_rex) lib/table_rex/renderer/text.ex:113: TableRex.Renderer.Text.render_title/1
    (table_rex) lib/table_rex/renderer/text.ex:81: TableRex.Renderer.Text.render/2
    (table_rex) lib/table_rex/table.ex:219: TableRex.Table.render!/2
    (tablerexbug) lib/tablerexbug.ex:38: Tablerexbug.table_fail/0
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```
Tested on Linux Mint 18 (Sarah), with esl-erlang version (1:20.1), elixir version (1.5.2-1).
I've attached the test code that I used.

[tablerexbug.tar.gz](https://github.com/djm/table_rex/files/1532369/tablerexbug.tar.gz)

**Comment by djm** [comment]
Hi Justin,

Thanks for the bug report - would you like to add a failing test (and a fix
if you're so inclined?)

Thanks!
Darian

**Comment by matt-harvey** [comment]
I tried and failed to reproduce this issue on master. See [this branch](https://github.com/matt-harvey/table_rex/tree/issue-22-not-reproduced-on-master).

I then reverted [this commit](https://github.com/djm/table_rex/pull/21/commits/1417cd4044ebe8440d197ab5fe81f8da20ed22d5), and tried again to reproduce the issue. This time I reproduced it successfully. See [this branch](https://github.com/matt-harvey/table_rex/tree/issue-22-reproduced-after-reverting-1417cd4044ebe8440d19).

So it seems that, when #13 was fixed, it fixed this issue also.

So I think this Issue can now be closed.

**Comment by djm** [comment]
Well, thanks very much for doing that Matt!

Closing for now, please reopen if anyone finds otherwise.

**Comment by matt-harvey** [comment]
No worries!
