### ISSUE TITLE
Bug when rendering string data

### ISSUE THREAD

**Issue by pawurb** [djm/table_rex#38]
Hi. Thanks for a great lib. I'm using it in https://github.com/pawurb/ecto_psql_extras . 

Recently we've encountered a bug when trying to render rows with string only data. 

You can reproduce it like that:

```elixir
columns = [:query, :exec_time, :prop_exec_time, :ncalls, :sync_io_time]

rows = [
  [
    "/* 10 queries that have the highest frequency of execution */\n\nSELECT query AS qry,\ninterval $1 * total_time AS exec_time,\nto_char((total_time/sum(total_time) OVER()) * $2, $3) || $4  AS prop_exec_time,\nto_char(calls, $5) AS ncalls,\ninterval $6 * (blk_read_time + blk_write_time) AS sync_io_time\nFROM pg_stat_statements WHERE userid = (SELECT usesysid FROM pg_user WHERE usename = current_user LIMIT $7)\nORDER BY calls DESC\nLIMIT $8",
    "0.001002 seconds",
    "0.012557063201070959",
    "2",
    "0 seconds"
  ],
  [
    "/* 10 queries that have the highest frequency of execution */\n\nSELECT $1 AS query,\ninterval $2 * total_time AS exec_time,\nto_char((total_time/sum(total_time) OVER()) * $3, $4) || $5  AS prop_exec_time,\nto_char(calls, $6) AS ncalls,\ninterval $7 * (blk_read_time + blk_write_time) AS sync_io_time\nFROM pg_stat_statements WHERE userid = (SELECT usesysid FROM pg_user WHERE usename = current_user LIMIT $8)\nORDER BY calls DESC\nLIMIT $9",
    "0.000404 seconds",
    "0.005062856392728202",
    "1",
    "0 seconds"
  ],
  [
    "CREATE EXTENSION pg_stat_statements",
    "0.056623 seconds",
    "0.7098017508490848",
    "1",
    "0 seconds"
  ],
  [
    "SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,\n       coalesce(d.typelem, t.typelem), coalesce(r.rngsubtype, $1), ARRAY (\n  SELECT a.atttypid\n  FROM pg_attribute AS a\n  WHERE a.attrelid = t.typrelid AND a.attnum > $2 AND NOT a.attisdropped\n  ORDER BY a.attnum\n)\nFROM pg_type AS t\nLEFT JOIN pg_type AS d ON t.typbasetype = d.oid\nLEFT JOIN pg_range AS r ON r.rngtypid = t.oid OR (t.typbasetype <> $3 AND r.rngtypid = t.typbasetype)\nWHERE (t.typrelid = $4)\nAND (t.typelem = $5 OR NOT EXISTS (SELECT $6 FROM pg_catalog.pg_type s WHERE s.typrelid != $7 AND s.oid = t.typelem))",
    "0.020626 seconds",
    "0.2585644066424921",
    "1",
    "0 seconds"
  ],
  [
    "/* 10 queries that have longest execution time in aggregate */\n\nSELECT query AS qry,\ninterval $1 * total_time AS exec_time,\nto_char((total_time/sum(total_time) OVER()) * $2, $3) || $4  AS prop_exec_time,\nto_char(calls, $5) AS ncalls,\ninterval $6 * (blk_read_time + blk_write_time) AS sync_io_time\nFROM pg_stat_statements WHERE userid = (SELECT usesysid FROM pg_user WHERE usename = current_user LIMIT $7)\nORDER BY total_time DESC\nLIMIT $8",
    "0.001118 seconds",
    "0.014013922914623996",
    "1",
    "0 seconds"
  ]
]

TableRex.quick_render!(rows, columns)
```
it produces: 

```
** (ArgumentError) argument error
    (stdlib) :binary.copy(" ", -402)
    (table_rex) lib/table_rex/renderer/text.ex:316: TableRex.Renderer.Text.do_render_cell/4
    (table_rex) lib/table_rex/renderer/text.ex:288: TableRex.Renderer.Text.render_cell/3
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (table_rex) lib/table_rex/renderer/text.ex:277: TableRex.Renderer.Text.render_cell_row/4
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (table_rex) lib/table_rex/renderer/text.ex:223: TableRex.Renderer.Text.render_rows/1
    (table_rex) lib/table_rex/renderer/text.ex:85: TableRex.Renderer.Text.render/2
```

Context: https://github.com/pawurb/ecto_psql_extras/issues/8

A fix or a tip what's wrong here would be highly appreciated because it currently breaks some features of my lib.

**Comment by pawurb** [comment]
The issue was caused by newline characters in query strings. I've managed to resolve it.

**Comment by djm** [comment]
Hi @pawurb!

Glad you managed to sort it, the error message could certainly be better.

Multi-line support is still an open issue (#7). I don't have the capacity to work on it at the minute - but it is available for anyone to pick up, should anyone else read this.
